server:
  port: 17300
spring:
  application:
    name: cloud-provider-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud2020?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: wang


eureka:
  client:

    register-with-eureka: true  # 默认注册到Eureka
    fetch-registry: true #单点Eureka无所谓  但是集群必须设置为true 这样Ribbon才能负载均衡
    service-url:
      defaultZone: http://localhost:18000/eureka/


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号隔离
  typeAliasesPackage: com.hzbs.payment.pojo
  global-config:
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_EMPTY
      table-underline: true
    #自定义填充策略接口实现
    #meta-object-handler: cn.com.yyxx.yld.config.SysMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false